package enums;

public enum BuildingType {
    BARRACKS , CAMP , GIANTS_CASTLE , TOWN_HALL,
    AIR_DEFENSE, CANNON, ARCHER_TOWER, WIZARD_TOWER, ELIXIR_MINE ,
    ELIXIR_STORAGE , GOLD_MINE , GOLD_STORAGE ,

    MINE , STORAGE , WALL , TRAP, DEFENSIVE_TOWER

}
