package enums;

public enum CommandType {
    NEW_GAME, LOAD_GAME, SAVE_GAME, STATUS, TURN, SHOW_BUILDINGS, RESOURCES, INFO, UPGRADE, BACK,
    SHOW_MENU, WHERE_AM_I, SOLDIERS, CAPACITY_INFO, MINE, SOURCES_INFO, TARGET, ATTACK_INFO, ITEM_NUMBER,
    EXIT, BOOLEAN , COORDINATE ,ELSE
    , ATTACK_MODE ,

    //for the attack part
    END_SELECT , PUT_UNIT , ONE_TURN ,  QUIT_ATTACK , STATUS_SOLDIER , STATUS_TOWER , STATUS_WAR , STATUS_RESOURCE
}